[package]
name = "diode"
version = "1.3.1"
edition = "2021"
license = "GPL-3.0"

[dependencies]
clap = { version = "4.1", features = ["derive"] }
crossbeam-channel = "0.5"
crossbeam-utils = "0.8"
fasthash = "0.4"
libc = "0.2"
log = "0.4"
rand = "0.8"
raptorq = "1.7"
simple_logger = "4.1"
nix = { version = "0.29", features = [ "socket" ]}

[dev-dependencies]
criterion = "0.5"
pprof = { version = "0.13", features = ["criterion", "flamegraph"] }
rand = "0.8"
rand_xorshift = "0.3"
human_bytes = { version = "0.4", default-features = false }

[profile.release]
lto = true
opt-level = 3
debug = false

[workspace]
members = [".", "diode-file-bindings"]

[[bench]]
name = "encoding"
harness = false

