[package]
name = "diode"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4"
crossbeam-channel = "0"
log = "0"
rand = "0"
raptorq = "1"
simple_logger = "4"

[lib]
name = "diode"
path = "src/diode.rs"

[[bin]]
name = "diode-down"
path = "src/down/main.rs"

[[bin]]
name = "diode-up"
path = "src/up/main.rs"

[profile.release]
lto = true
opt-level = 3
debug = false
