[package]
name = "diode"
version = "1.2.2"
edition = "2021"
license = "GPL-3.0"

[dependencies]
clap = "4.1"
crossbeam-channel = "0.5"
crossbeam-utils = "0.8"
fasthash = "0.4"
libc = "0.2"
log = "0.4"
rand = "0.8"
raptorq = "1.7"
simple_logger = "4.1"

[profile.release]
lto = true
opt-level = 3
debug = false

[workspace]
members = [".", "diode-file-bindings"]
